### ISSUE TITLE
Project Peer Review Issues and Content Recommendations

### ISSUE THREAD

**Issue by dkovalenko420** [mayasujanto/MyPersonalWebsite#2]
Issues:
1. There is a bug when you open different pages, the size of the navigation bar changes. For example, when switching between index.html and aboutme.html, the size of the navigation bar changes.

2. In portfolio.html, there is a bug that stops buttons from changing back in color after you click them once. Specifically, when you click "Show All", "Prints", "Social" and "Newsletters", they stay dark grey regardless of which button you click.

Content:
1. I would recommend adding a few sentences describing your leadership and professional experiences in work.html, which would add a sense of credibility to your experiences.

2. You could also add a page describing your educational background. This would make your portfolio even stronger. For example, you could add information regarding your experiences at Babson.

**Comment by mayasujanto** [comment]
Thank you for your feedback!
