### ISSUE TITLE
Peer Review Suggestions from Dave

### ISSUE THREAD

**Issue by daveyc1234** [mayasujanto/MyPersonalWebsite#3]
Technical Suggestions:

1) You have made some real progress on your site! I went through a lot and it was hard to find suggestions! The first I ran into was on the submit page. When you submit the form, it says 405 not allowed.

2) On the portfolio page, make the "client gift stickers" the same length as your other products by changing the border length to be the same as the others.

Content:

1) You could add more flare in your form page by adding css in your style. 

2) For the portfolio page, you could add borders to the names of the pictures. I think that would look great.

**Comment by mayasujanto** [comment]
Thank you for your feedback Dave!
